name: Feature request
description: Suggest an idea for this project

body:
  - type: textarea
    id: feature-description
    attributes:
      label: Describe the feature you'd like.
    validations:
      required: true